#!/usr/bin/env python3
"""generate the badge's idle-screen bitmap as a rust source file.

the vault draws `bitmaps::dc_logo::BITMAP`, a `[u32; 512]`, which is a 128x128
one-bit-per-pixel framebuffer: pixel i is bit (i % 32) of word (i / 32), LSB-first,
row-major. that is the same layout `cmds/image.rs` assembles, so the packing here is
shared with tools/oled.py.

  ./tools/make_badge_art.py --pfp ~/Downloads/rjZaQbf7.jpg \
      --out ../dc34-vault/src/bitmaps/dc_logo.rs --preview /tmp/card.png

the panel is small and one-bit, so the design leans on silhouette rather than detail:
the pfp is dithered inside a circular mask, the name is set large, pronouns sit under
it, and a few stars fill the corners.
"""

import argparse
import pathlib
import subprocess
import sys

from PIL import Image, ImageDraw, ImageFont, ImageOps

W = H = 128
WORDS = W * H // 32

FONT_CANDIDATES = [
    "/nix/store/6sxv3pjlx8xb73jbnfgplbdn1qb42i7k-dejavu-fonts-2.37/share/fonts/truetype/DejaVuSans-Bold.ttf",
    "/nix/store/6sxv3pjlx8xb73jbnfgplbdn1qb42i7k-dejavu-fonts-2.37/share/fonts/truetype/DejaVuSansMono-Bold.ttf",
]


def font(size: int, bold: bool = True):
    paths = list(FONT_CANDIDATES)
    try:
        q = "sans-serif:bold" if bold else "sans-serif"
        found = subprocess.run(["fc-match", "-f", "%{file}", q],
                               capture_output=True, text=True, timeout=5).stdout.strip()
        if found:
            paths.append(found)
    except (OSError, subprocess.SubprocessError):
        pass
    for p in paths:
        try:
            return ImageFont.truetype(p, size)
        except OSError:
            continue
    return ImageFont.load_default()


def centred(d: ImageDraw.ImageDraw, y: int, text: str, f, fill=1) -> int:
    box = d.textbbox((0, 0), text, font=f)
    d.text(((W - (box[2] - box[0])) // 2 - box[0], y), text, font=f, fill=fill)
    return box[3] - box[1]


def star(d: ImageDraw.ImageDraw, cx: int, cy: int, r: int) -> None:
    """a tiny four-point sparkle. reads better than a 5-point star at this size."""
    d.line([cx - r, cy, cx + r, cy], fill=1)
    d.line([cx, cy - r, cx, cy + r], fill=1)
    d.point([(cx - 1, cy - 1), (cx + 1, cy - 1), (cx - 1, cy + 1), (cx + 1, cy + 1)], fill=1)


def build(pfp_path: pathlib.Path, name: str, pronouns: str, threshold: int) -> Image.Image:
    canvas = Image.new("1", (W, H), 0)
    d = ImageDraw.Draw(canvas)

    # --- the pfp, dithered inside a circle -----------------------------------
    size = 62
    src = Image.open(pfp_path).convert("L")
    src = ImageOps.autocontrast(src.resize((size, size), Image.LANCZOS))
    # threshold, not dither. the pfp is flat pastel line art, so error diffusion turns
    # it into noise, while a hard cut keeps the silhouette: hair, the closed eye, the
    # plush. compared side by side before choosing.
    src = src.point(lambda v: 255 if v > threshold else 0, "1")

    mask = Image.new("1", (size, size), 0)
    ImageDraw.Draw(mask).ellipse([0, 0, size - 1, size - 1], fill=1)

    px, py = (W - size) // 2, 4
    canvas.paste(src, (px, py), mask)
    d.ellipse([px - 2, py - 2, px + size + 1, py + size + 1], outline=1)

    # --- name and pronouns ----------------------------------------------------
    y = py + size + 6
    centred(d, y, name, font(22))
    y += 24
    centred(d, y, pronouns, font(13))

    # --- sparkles in the corners ---------------------------------------------
    for cx, cy, r in ((12, 14, 4), (116, 20, 3), (10, 92, 3), (118, 88, 4)):
        star(d, cx, cy, r)

    return canvas


def pack(img: Image.Image) -> list:
    px = img.load()
    words = [0] * WORDS
    for yy in range(H):
        for xx in range(W):
            if px[xx, yy]:
                i = yy * W + xx
                words[i // 32] |= 1 << (i % 32)
    return words


def emit_rust(words: list, source: str) -> str:
    lines = [
        "#![cfg_attr(rustfmt, rustfmt_skip)]",
        f"// generated by tools/make_badge_art.py from {source}",
        "// 128x128 1bpp, pixel i = bit (i % 32) of word (i / 32), LSB-first, row-major",
        "pub const BITMAP: [u32; 512] = [",
    ]
    for i in range(0, len(words), 4):
        row = ", ".join(f"0x{w:08x}" for w in words[i:i + 4])
        lines.append(f"  {row},")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pfp", type=pathlib.Path, required=True)
    ap.add_argument("--name", default="vmfunc")
    ap.add_argument("--pronouns", default="it/its")
    ap.add_argument("--out", type=pathlib.Path, required=True)
    ap.add_argument("--threshold", type=int, default=140,
                    help="1-bit cut point for the pfp, 0-255 (default 140)")
    ap.add_argument("--preview", type=pathlib.Path)
    args = ap.parse_args()

    if not args.pfp.is_file():
        print(f"error: {args.pfp} not found", file=sys.stderr)
        return 1

    img = build(args.pfp, args.name, args.pronouns, args.threshold)
    if args.preview:
        img.save(args.preview)
        print(f"[*] preview -> {args.preview}")

    words = pack(img)
    args.out.write_text(emit_rust(words, args.pfp.name))
    lit = sum(bin(w).count("1") for w in words)
    print(f"[+] wrote {args.out} ({lit} pixels lit of {W * H})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
